# fly.toml app configuration file for tn-pds-crawler
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tn-pds-crawler'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "tn_pds_data"
  destination = "/app/data"

[processes]
  app = ""
  cron = "cron -f"

[env]
  PYTHONUNBUFFERED = "1"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
