[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "" # Use the Dockerfile directly

[deploy]
startCommand = "/app/entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 # Increased retries

[deploy.resources]
CPU = 1024
Memory = 1024

[volumes.data]
mountPath = "/app/data"
path = "/app/data"
