services:
  - type: web
    name: tn-pds-crawler
    env: docker
    plan: standard
    region: singapore
    buildCommand: docker build -t tn-pds-crawler .
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: 1
    disk:
      name: tn-pds-data
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
